# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: csabakollar/gcloud
# Command to start on workspace startup (optional)
tasks: []
  #- init: yarn install
  #  command: yarn build
# Ports to expose on workspace startup (optional)
ports: []
  #- port: 8000
  #  onOpen: open-preview
