# The Docker image to run your workspace in. Defaults to gitpod/workspace-full
image: eu.gcr.io/sab-lab-sbx-01-3590/y:p9cs19
# Command to start on workspace startup (optional)
tasks: []
  #- init: yarn install
  #  command: yarn build
# Ports to expose on workspace startup (optional)
ports: []
  #- port: 8000
  #  onOpen: open-preview

vscode:
  extensions:
    - hashicorp.terraform@2.2.3:bBQoMVR7TCwCZWURotrh3w==
    - jebbs.plantuml@2.13.12:q7DiD6H5NTesaWYIXmeMMQ==
    - BazelBuild.vscode-bazel@0.4.0:CNqPe08EnThWfsQXBuinsQ==
    - golang.go@0.17.2:WOyuUIRDocFQQa791wKwRQ==
    - timonwong.shellcheck@0.10.1:J9QwQEqo5+bxqMMZDnFUNQ==
